services:
  cloud:
    build: ./cloud
    restart: always
    expose:
      - "80"
    depends_on:
      - mongo
      - redis

  web:
    build:
      context: ./interface
      dockerfile: web/Dockerfile
    restart: always
    expose:
      - "80"

  mongo:
    image: mongo:8
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

  redis:
    image: redis:8
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  nginx:
    image: nginx:1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./config/nginx/ssl/certs:/etc/ssl/certs/
      - ./config/nginx/ssl/private:/etc/ssl/private
    depends_on:
      - cloud
      - web
      - code

  code:
    build:
      context: .
      dockerfile: tools/code/Dockerfile
    restart: always
    ports:
      - "8080:8080"
      - "3000:3000"
      - "5000:5000"
      - "9010:9010"
    volumes:
      - ./:/home/coder/project
      - ~/.ssh:/home/coder/.ssh:ro
      - ./config/code:/home/coder/.config/code-server
      - ./tools/code/data:/home/coder/.local/share/code-server
    environment:
      - DOCKER_USER=coder

volumes:
  mongo:
  redis:
