services:
  cloud:
    build: ./cloud
    restart: always
    depends_on:
      - mongo
      - redis

  web:
    build:
      context: ./interface
      dockerfile: web/Dockerfile
    restart: always

  mongo:
    image: mongo:8
    restart: always
    volumes:
      - mongo:/data/db

  redis:
    image: redis:8
    restart: always
    volumes:
      - redis:/data

  nginx:
    image: nginx:1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./config/nginx/ssl/certs:/etc/ssl/certs/
      - ./config/nginx/ssl/private:/etc/ssl/private
    depends_on:
      - cloud
      - web
      - code

  code:
    user: root
    build:
      context: .
      dockerfile: tools/code/Dockerfile
    restart: always
    volumes:
      - ./:/home/coder/project
      - ~/.ssh:/root/.ssh
      - ./config/code:/root/.config/code-server
      - ./tools/code/data:/root/.local/share/code-server
    environment:
      - DOCKER_USER=root

volumes:
  mongo:
  redis:
