services:
  cloud:
    build: ./cloud
    restart: always
    expose:
      - "80"
    depends_on:
      - mongo
      - redis

  web:
    build:
      context: ./interface
      dockerfile: web/Dockerfile
    restart: always
    expose:
      - "80"

  mongo:
    image: mongo:8
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

  redis:
    image: redis:8
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  nginx:
    image: nginx:1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./config/nginx/ssl/certs:/etc/ssl/certs/
      - ./config/nginx/ssl/private:/etc/ssl/private
    depends_on:
      - cloud
      - web
      - code
      - preview

  code:
    image: codercom/code-server:latest
    restart: always
    expose:
      - "8080"
    volumes:
      - ./:/home/coder/project
      - ./config/code:/home/coder/.config/code-server
    environment:
      - DOCKER_USER=coder

  preview:
    image: node:20
    command: npm run dev:web
    restart: always
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
    working_dir: /app/web
    volumes:
      - ./interface:/app
      - /app/web/node_modules

volumes:
  mongo:
  redis:
